#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path.cwd()
TODAY = "2026-08-04"

SKILLS = {
"regulated-product-context": {
"description": "Normalisiert bestätigten Produkt-, Intended-Purpose-, Markt-, Lifecycle-, QMS-, Risiko-, Software-, AI-, Privacy- und Evidenzkontext für regulierte Medizinprodukte und IVDs, ohne Klassifikation oder Zulassung zu erfinden.",
"requires": [],
"outputs": ["regulated-product-context.json", "regulated-product-context.md"],
"purpose": "Ein gemeinsamer, zeitpunktbezogener Produktkontext verhindert, dass nachgelagerte RA/QM-Skills dieselben Basisfragen erneut stellen oder widersprüchliche Annahmen verwenden.",
"trigger": "Verwenden, wenn Grilling-Reports, Specs, technische Dokumentation oder Evidenz in eine gemeinsame Ausgangslage für Medical Device/IVD Engineering überführt werden sollen.",
"rules": ["Trenne Fakten, bestätigte Entscheidungen, Annahmen, Hypothesen, Unbekannte und Konflikte sichtbar.","Kennzeichne Produktart mindestens als medical-device, ivd, samd, accessory, combination, other oder unknown.","Behandle Intended Purpose, Claims, Zielpopulation, Anwender, Use Environment, Märkte und Lifecycle-Phase als explizite Felder.","Bei IVD zusätzlich mindestens Specimen, Analyte/Measurand, Untersuchungsprinzip und qualitative/quantitative Nutzung erfassen, soweit bekannt.","Regulatorische Klassifikation besitzt einen Evidenzstatus confirmed, hypothesis oder unknown; eine bloße Ableitung wird nie als behördlich bestätigt dargestellt.","Jeder zeitabhängige regulatorische Fakt erhält asOf und Source-Referenz oder bleibt unknown.","Software, Connectivity, AI/ML, personenbezogene Daten, besondere Kategorien personenbezogener Daten und Cybersecurity-Relevanz werden als eigener Kontext geführt."],
"workflow": ["Bestätigte Grilling-/Spec-/Repository- und Evidenzquellen inventarisieren.","Produkt, Intended Purpose/Claims, Märkte, Lifecycle, QMS, klinische bzw. Performance-Evidenz, Herstell-/Supplier-, Software/AI-, Security- und Privacy-Kontext normalisieren.","Widersprüche und fehlende entscheidungsrelevante Angaben markieren.","Stabile JSON-Sicht plus lesbares Markdown erzeugen.","Nur offene, entscheidungsrelevante Unsicherheiten als Investigations an large-work-wayfinder übergeben."],
"boundaries": ["Kein eigener regulatorischer Klassifizierer oder Zulassungsentscheid.","Keine erneute Requirements-Befragung für bereits bestätigte Grilling-Inhalte.","Keine Speicherung von Secrets oder unnötigen personenbezogenen Rohdaten."],
"anchors": ["confirmed, hypothesis oder unknown","Jeder zeitabhängige regulatorische Fakt erhält asOf","Specimen, Analyte/Measurand"]},
"evidence-based-causal-investigation": {
"description": "Untersucht Qualitäts-, Prozess-, Produkt-, Herstellungs-, Human-Factor- und Systemprobleme evidenzbasiert mit konkurrierenden Kausalhypothesen und verifiziertem oder ausdrücklich unbestätigtem Root Cause.",
"requires": ["research-to-evidence-note"],"outputs": ["causal-investigation.json","causal-investigation.md"],
"purpose": "Überträgt die Evidenzdisziplin von Softwarediagnosen auf nicht-softwarezentrierte Nonconformities, Complaints, Audit Findings und Prozessabweichungen.",
"trigger": "Verwenden, wenn eine CAPA-, Nonconformity-, Complaint- oder Audit-Ursache untersucht werden muss und 5-Why/Fishbone/FMEA/FTA nicht als bloße Ritualmethoden genügen.",
"rules": ["Symptom, unmittelbare Ursache, beitragende Bedingung und Root Cause sind getrennte Begriffe.","Eine Root-Cause-Behauptung benötigt unterscheidende Evidenz gegenüber plausiblen Alternativhypothesen.","5-Why, Ishikawa, FTA, FMEA, Fault Isolation oder Human-Factors-Methoden sind Werkzeuge, keine Beweise.","Human error ist ohne Prüfung von System-, Prozess-, Training-, Interface-, Workload- und Kontrollbedingungen kein hinreichender Endpunkt.","Containment, Correction, Corrective Action und Preventive/Systemic Action bleiben getrennt.","Fehlende oder widersprüchliche Evidenz führt zu rootCause.status=unverified statt zu einer plausiblen Geschichte."],
"workflow": ["Problem und objektive Evidenz zeitlich und sachlich eingrenzen.","Konkurrierende Kausalhypothesen mit erwarteten Beobachtungen formulieren.","Mit unterscheidenden Nachweisen Hypothesen bestätigen, widerlegen oder offen lassen.","Root Cause und beitragende Bedingungen abgrenzen.","Nur evidenzgestützte Action Targets an CAPA/Risk/QMS übergeben.","Restrisiko und offene Untersuchungen dokumentieren."],
"boundaries": ["Keine automatische CAPA-Eröffnung oder Closure.","Keine Schuldzuweisung an Personen.","Keine Methode erzwingt eine bestimmte Anzahl von Why-Schritten oder Ursachen."],"anchors": ["Werkzeuge, keine Beweise","rootCause.status=unverified","Containment, Correction, Corrective Action"]},
"two-axis-compliance-review": {
"description": "Prüft regulierte Anforderungen getrennt nach Anwendbarkeit/Abdeckung und nach Evidenz/Wirksamkeit, damit fehlende Nachweise nicht als Compliance und grüne Checklisten nicht als effektive Controls gelten.",
"requires": ["research-to-evidence-note"],"outputs": ["compliance-requirement-coverage.json","compliance-evidence-effectiveness.json","compliance-review-decision.md"],
"purpose": "Stellt einen gemeinsamen Review-Kern für QMS-, ISMS-, Regulatory- und Privacy-Assessments bereit.","trigger": "Verwenden, wenn eine Gap Analysis, Audit-Readiness, technische Dokumentation, Control-Implementierung oder regulatorische Anforderung bewertet wird.",
"rules": ["Achse 1 bewertet requirement applicability und coverage; Achse 2 bewertet evidence sufficiency und control/process effectiveness.","Jede normative Aussage verweist auf eine regulatorische Quelle, einen Standard, Guidance, Organisationspolicy oder ausdrücklich markierte Interpretation.","Missing evidence ist unknown oder gap, niemals compliant.","Ein Compliance-Prozentscore darf höchstens als organisationsdefinierter Indikator erscheinen und ersetzt keine Einzelbefunde.","Audit-Finding-Schweregrade, Samplegrößen und Fristen werden nicht als universelle Normvorgaben erfunden.","Eine positive Gesamtentscheidung setzt voraus, dass keine entscheidende Anforderung oder Evidenzlücke verborgen bleibt."],
"workflow": ["Scope, Jurisdiktion, Kriterien und asOf fixieren.","Anforderungen inventarisieren und Anwendbarkeit mit Evidenzstatus bestimmen.","Coverage unabhängig von Evidenzqualität bewerten.","Nachweise, Stichprobenlogik und Wirksamkeit getrennt prüfen.","Widersprüche, unknowns und Finding-Kandidaten ableiten.","Review-Entscheidung mit Restrisiken und nächstem verifizierbaren Schritt erzeugen."],
"boundaries": ["Kein Ersatz für Zertifizierer, Benannte Stelle, Behörde oder Rechtsberatung.","Keine automatische Freigabe nur wegen vollständiger Dokumentenliste.","Keine universellen Audit-Samplegrößen oder Finding-Klassen erfinden."],"anchors": ["Missing evidence ist unknown oder gap","Achse 1 bewertet requirement applicability","Compliance-Prozentscore"]},
"medical-device-risk-management-iso14971": {
"description": "Führt Medical-Device- und IVD-Risikomanagement nach dem Prozessmodell von ISO 14971 evidenzbasiert durch, ohne eine bestimmte Risikomatrix, RPN-Schwelle oder ALARP-Regel als Normvorgabe zu erfinden.",
"requires": ["regulated-product-context","research-to-evidence-note"],"outputs": ["risk-management-analysis.json","risk-management-analysis.md","risk-wayfinding-handoff.json"],
"purpose": "Verbindet Produktkontext, Hazard Analysis, Risk Controls, Residual Risk und Produktions-/Postproduktionsinformationen mit Engineering und regulatorischer Traceability.","trigger": "Verwenden für Risk Management Plan/File, Hazard Analysis, FMEA/FTA/Use Error Analysis, Residual Risk, Benefit-Risk oder Post-Market-Risk-Updates bei Medical Devices und IVDs.",
"rules": ["ISO 14971:2019 bleibt der fachliche Referenzrahmen, aber konkrete Normanforderungen werden nur aus zugänglicher autoritativer Evidenz behauptet.","Risikokriterien und Akzeptanzgrenzen sind organisationsdefiniert; 5x5-Matrix, RPN und ALARP sind optionale Methoden, keine universelle Normvorgabe.","Trenne Hazard, Sequence of Events, Hazardous Situation, Harm, Probability und Severity nachvollziehbar.","Risk Controls werden mit Implementierungs- und Wirksamkeitsverifikation verknüpft; ein niedriger Score ersetzt die Verification nicht.","Residual Risk, Overall Residual Risk und Benefit-Risk werden nur dort bewertet, wo Kontext und Kriterien dies tragen.","Produktions- und Postproduktionsinformationen können neue Hazards, Wahrscheinlichkeiten, Controls oder CAPA-Investigations auslösen.","AI/ML- und Cybersecurity-Risiken werden in denselben Lifecycle-Prozess integriert, ohne Security Engineering zu duplizieren."],
"workflow": ["Scope, Intended Purpose, Lifecycle und organisationsdefinierte Akzeptanzkriterien fixieren.","Hazards und vorhersehbare Ereignisfolgen evidenzbasiert identifizieren.","Risiken nach bestätigter Organisationsmethodik evaluieren.","Risk Controls priorisieren, implementierungs- und wirksamkeitsbezogene Verification planen.","Residual/Overall Residual Risk und erforderliche Benefit-Risk-Rationale dokumentieren.","Production/Post-production Signals, offene Investigations und Traceability übergeben."],
"boundaries": ["Keine erfundene Zertifizierungs- oder Regulatory-Acceptance-Aussage.","Keine FMEA-RPN-Schwelle als Ersatz für Risk Acceptability.","Keine Penetration Tests, klinischen Studien oder CAPA-RCA selbst ausführen."],"anchors": ["5x5-Matrix, RPN und ALARP sind optionale Methoden","Hazard, Sequence of Events, Hazardous Situation, Harm","Production/Post-production Signals"]},
"medical-device-qms-iso13485": {
"description": "Bewertet und strukturiert ein Medical-Device-/IVD-QMS gegen ISO 13485 sowie anwendbare regulatorische Ergänzungen, ohne Zertifizierung, FDA-Compliance oder feste Organisationsprozesse zu erfinden.",
"requires": ["regulated-product-context","two-axis-compliance-review"],"outputs": ["qms-gap-analysis.json","qms-process-map.json","qms-readiness.md"],
"purpose": "Stellt QMS-Scope, Prozesse, Evidence Gaps und regulatorische Schnittstellen so bereit, dass Engineering, Audit, CAPA und Management Review dieselbe Grundlage verwenden.","trigger": "Verwenden für ISO-13485-QMS-Aufbau/Remediation, QMSR-Gap-Analyse, Supplier Quality, Process Validation, Design/Development-QMS-Integration oder digitale/eQMS-Readiness.",
"rules": ["ISO 13485:2016 ist der aktuelle internationale QMS-Referenzstandard; konkrete Klauselbehauptungen benötigen autoritative Evidenz.","Für die USA gilt seit 2026-02-02 QMSR in 21 CFR Part 820 mit Incorporation by Reference von ISO 13485:2016; ISO-Zertifizierung allein beweist keine FDA-Compliance.","QMS-Scope, regulatorische Rollen, Prozesslandschaft, Interaktionen, Records und Verantwortlichkeiten bleiben explizit.","Supplier Controls, Process Validation, Design/Development, Complaint/CAPA, Audit und Management Review werden als verknüpfte Prozesse behandelt, nicht als isolierte Checklisten.","Part 11/Annex 11/eQMS-Anforderungen werden nur bei anwendbarem digitalen Record-/Signature-Kontext geprüft.","Missing evidence bleibt gap/unknown und wird nicht durch typische SOP-Listen geschlossen."],
"workflow": ["Organisations-/Produkt-/Markt-Scope und anwendbare Regulatory Requirements festlegen.","QMS-Prozesse und Interfaces kartieren.","Anforderungscoverage und Evidenzwirksamkeit über two-axis-compliance-review prüfen.","Process-/Supplier-/Validation-/Document-/CAPA-/Audit-Gaps priorisieren.","Readiness, Blocker, Investigations und sichere nächste Schritte ausgeben."],
"boundaries": ["Keine Zertifizierungszusage.","Kein Ersatz für product-specific Design Inputs/Outputs oder Testprotokolle.","Keine Behauptung, QMSR sei identisch mit ISO 13485 ohne US-spezifische Ergänzungen."],"anchors": ["seit 2026-02-02 QMSR","ISO-Zertifizierung allein beweist keine FDA-Compliance","Missing evidence bleibt gap/unknown"]},
"controlled-quality-documentation": {
"description": "Prüft und entwirft kontrollierte QMS-Dokument- und Record-Lifecycles mit Change Impact, Approval Evidence, Effective/Superseded State und Traceability, ohne eine feste Nummerierung oder DMS-Implementierung vorzuschreiben.",
"requires": ["regulated-product-context","two-axis-compliance-review"],"outputs": ["document-control-assessment.json","change-impact-assessment.json","controlled-document-plan.md"],
"purpose": "Schließt die Dokumentationslücke zwischen QMS-Regeln und Engineering-Artefakten, ohne ein zweites Dokumentensystem zu bauen.","trigger": "Verwenden für SOP-/WI-/Form-/Spec-/Technical-Documentation-Lifecycle, Change Control, Approval/Review, Training Impact, Record Retention oder elektronische Records/Signatures.",
"rules": ["Dokumenttypen, Nummerierung, Approval Matrix und Reviewfrequenzen sind organisationsdefiniert, sofern keine anwendbare regulatorische Quelle etwas Spezifischeres verlangt.","Lifecycle trennt mindestens draft, review, approved, effective, superseded und obsolete/retained, soweit organisationsseitig verwendet.","Ein Change Impact prüft mindestens Training, Validation, Regulatory, Risk, Supplier, Software/System, Related Documents und Records.","Approved oder effective darf nur behauptet werden, wenn die erforderliche externe/organisatorische Evidenz vorliegt.","Obsolete/superseded Inhalte werden am Point of Use gegen unbeabsichtigte Verwendung kontrolliert und gemäß Retention-Regeln erhalten.","Elektronische Records/Signatures werden nur bei tatsächlicher Anwendbarkeit gegen aktuelle Part-11-/Annex-11-/lokale Anforderungen geprüft."],
"workflow": ["Dokument-/Record-Typ, Scope und geltende Policy/Regulatory Criteria fixieren.","Lifecycle, Rollen, Review/Approval und Distribution/Access aufnehmen.","Change Impact und abhängige Artefakte bestimmen.","Evidenz für Approval, Effective Date, Training/Validation und Supersession prüfen.","Traceability und offene Compliance-/Migration-Gaps ausgeben."],
"boundaries": ["Keine feste Dokumentnummerierung erfinden.","Kein DMS/eQMS implementieren.","Keine E-Signature-Compliance aus bloßem Vorhandensein einer elektronischen Signatur ableiten."],"anchors": ["Nummerierung, Approval Matrix und Reviewfrequenzen sind organisationsdefiniert","Training, Validation, Regulatory, Risk","Approved oder effective darf nur behauptet werden"]},
"medical-device-capa": {
"description": "Strukturiert CAPA von Signal/Problem Statement über evidenzbasierte Kausalinvestigation, Action Plan und Effectiveness Verification bis zur kontrollierten Closure und Rückkopplung in Risk/QMS.",
"requires": ["evidence-based-causal-investigation","medical-device-risk-management-iso14971","medical-device-qms-iso13485"],"outputs": ["capa-plan.json","capa-effectiveness-plan.json","capa-status.md"],
"purpose": "Verhindert schematische CAPA-Routinen und koppelt Root Cause, Actions, Effectiveness und Risk/QMS-Updates nachweisbar.","trigger": "Verwenden für CAPA-Bewertung und -Planung nach Complaint, Nonconformity, Audit Finding, Trend, Supplier-/Process-/Product-Problem oder Post-Market Signal.",
"rules": ["CAPA-Notwendigkeit folgt anwendbaren regulatorischen/QMS-Kriterien und risikobasierter Bewertung; eine feste Wiederholungsanzahl ist keine universelle Regel.","Containment, Correction, Corrective Action, Preventive/Systemic Action und Risk Control sind getrennte Action Types.","Root Cause wird aus evidence-based-causal-investigation übernommen und bleibt unverified, wenn die Evidenz nicht genügt.","Jede Action nennt Ursache/Risiko-Bezug, Owner-Status, Due-Date-Status, Preconditions und objektive Completion Evidence.","Effectiveness Criteria und Beobachtungsfenster werden vor Closure definiert und müssen zur behaupteten Ursache passen.","Closed wird nur bei bestätigter Implementierung, ausreichender Effectiveness Evidence und erforderlicher Risk/QMS/Document-Update-Evidenz ausgegeben."],
"workflow": ["Signal, Scope, Risiko und CAPA-Kriterien bestimmen.","Containment/Correction von systemischer Investigation trennen.","Verifizierte/ungeklärte Ursachen übernehmen.","Actions mit Traceability und Effectiveness Criteria planen.","Implementierungs- und Effectiveness Evidence prüfen.","Closure Readiness sowie Risk/QMS/Document-Feedback ausgeben."],
"boundaries": ["Keine automatische Closure.","Keine universelle 3x-Wiederholungsregel.","Keine Person als Root Cause ohne Systemanalyse."],"anchors": ["feste Wiederholungsanzahl ist keine universelle Regel","Effectiveness Criteria und Beobachtungsfenster","Closed wird nur bei bestätigter Implementierung"]},
"eu-mdr-ivdr-regulatory-specialist": {
"description": "Bewertet EU-Market-Access für Medical Devices und IVDs getrennt nach MDR 2017/745 und IVDR 2017/746 mit evidenzgebundener Klassifikationshypothese, Technical Documentation, Clinical/Performance Evaluation und Post-Market-Pflichten.",
"requires": ["regulated-product-context","research-to-evidence-note","medical-device-risk-management-iso14971"],"outputs": ["eu-regulatory-assessment.json","eu-regulatory-assessment.md","eu-regulatory-investigations.json"],
"purpose": "Ersetzt einen MDR-only-Pfad durch einen gemeinsamen EU-Spezialisten, der Device und IVD sauber trennt und volatile Implementierungsdetails nicht als zeitlose Konstanten speichert.","trigger": "Verwenden für MDR/IVDR-Anwendbarkeit, Klassifikation, Conformity Assessment, GSPR, Technical Documentation, Clinical Evaluation/Investigation, Performance Evaluation/Study, PMS/PMCF/PMPF, UDI/EUDAMED oder NB-Strategie.",
"rules": ["Zuerst Device/IVD-Anwendbarkeit bestimmen; MDR 2017/745 und IVDR 2017/746 werden nie vermischt.","Klassifikation ist eine evidenzbasierte Hypothese mit Regel-/Anhangsreferenz, bis die erforderliche fachliche/behördliche/Notified-Body-Bestätigung vorliegt.","Bei IVD unterscheiden sich Performance Evaluation, Scientific Validity, Analytical Performance, Clinical Performance und gegebenenfalls Performance Studies von MDR Clinical Evaluation.","PMCF und PMPF werden nicht synonym verwendet.","Conformity Assessment, Benannte-Stelle-Beteiligung, UDI/EUDAMED-Status, Übergangsregeln und MDCG-Guidance werden mit aktuellem asOf und offizieller Quelle behandelt.","Technical Documentation wird über Compliance Traceability mit Risk, V&V, Clinical/Performance Evidence, Labeling und PMS verbunden.","Keine regulatorische Freigabe oder CE-Konformität wird allein aus einer internen Checkliste behauptet."],
"workflow": ["Regime MDR vs IVDR und Produktkontext fixieren.","Anwendbare Klassifikationsregeln/Conformity Route als Evidence-backed Assessment bestimmen.","Technical Documentation/GSPR- und Clinical-/Performance-Evidence-Gaps prüfen.","PMS/PMCF/PMPF, UDI/EUDAMED und NB-Abhängigkeiten mit Freshness erfassen.","Blocker, Investigations und Market-Access-Readiness ausgeben."],
"boundaries": ["Keine endgültige Klassifikationsentscheidung ohne angemessene Bestätigung.","Keine Volltexte urheberrechtlich geschützter Standards reproduzieren.","Keine Transition Dates oder Guidance-Versionen ohne aktuelle offizielle Quelle als zeitlos darstellen."],"anchors": ["MDR 2017/745 und IVDR 2017/746 werden nie vermischt","PMCF und PMPF werden nicht synonym","Klassifikation ist eine evidenzbasierte Hypothese"]},
"fda-medical-device-ivd-regulatory-specialist": {
"description": "Bewertet US-FDA-Regulatory-Pathways für Medical Devices und IVDs einschließlich 510(k), De Novo, PMA, Exemption/Classification, IVD-spezifischer Controls und QMSR-Readiness mit aktueller FDA-Evidenz.",
"requires": ["regulated-product-context","research-to-evidence-note","medical-device-qms-iso13485"],"outputs": ["fda-regulatory-assessment.json","fda-regulatory-assessment.md","fda-regulatory-investigations.json"],
"purpose": "Stellt einen aktuellen US-Pfad bereit, der IVDs einschließt und den seit 2026 geltenden QMSR-Rahmen statt veralteter QSR-Checklisten verwendet.","trigger": "Verwenden für FDA Classification/Product Code, Predicate/SE, 510(k), De Novo, PMA, Pre-Sub/Q-Sub, eSTAR, IVD/CLIA-Kontext, Cybersecurity-Premarket-Evidence oder QMSR Readiness.",
"rules": ["Der regulatorische Pathway wird aus aktueller FDA-Klassifikation, Intended Use, Technological Characteristics, Predicate-/Novelty-Evidence und Risk abgeleitet; er bleibt Assessment bis zur behördlichen Entscheidung.","Seit 2026-02-02 gilt QMSR in 21 CFR Part 820 und incorporates by reference ISO 13485:2016; US-spezifische Anforderungen bleiben separat nachzuweisen.","IVDs werden als eigene Device-Kategorie mit anwendbaren IVD-, Labeling-, Premarket-, Postmarket- und gegebenenfalls CLIA-Aspekten behandelt.","Predicate, Product Code, Recognized Standards, Guidance, Submission Format, User Fees und Review-Ziele sind volatile FDA-Fakten und benötigen aktuelle offizielle Quelle/asOf.","Keine feste User-Fee oder Review-Dauer wird als Skill-Konstante verwendet.","Laboratory-/LDT-, AI/PCCP-, Cybersecurity- oder Enforcement-Themen werden nur mit aktueller FDA-Evidenz bewertet."],
"workflow": ["Intended Use, Device/IVD-Typ, US-Ziel und vorhandene FDA-Identifiers erfassen.","Aktuelle Classification/Product-Code/Predicate-Evidenz recherchieren und Pathway-Hypothese begründen.","Submission-/Testing-/Software-/Cybersecurity-/IVD-Evidence-Gaps strukturieren.","QMSR- und US-specific Quality Requirements separat prüfen.","Pre-Sub-/Investigation-Bedarf, Blocker und Readiness ausgeben."],
"boundaries": ["Keine FDA-Clearance/Approval behaupten ohne behördliche Evidenz.","Keine statischen Fees oder MDUFA-Zeiten.","Keine Behauptung, ISO-13485-Zertifizierung ersetze QMSR-Compliance."],"anchors": ["Seit 2026-02-02 gilt QMSR","Keine feste User-Fee oder Review-Dauer","IVDs werden als eigene Device-Kategorie"]},
"medical-device-isms-governance": {
"description": "Strukturiert ISO-27001-orientierte ISMS-Governance für MedTech/IVD-Organisationen und koppelt Informationssicherheitsrisiken, Controls, Supplier/Cloud, Incidents und Product-Cybersecurity-Schnittstellen ohne technische Security-Tests zu duplizieren.",
"requires": ["regulated-product-context","two-axis-compliance-review"],"outputs": ["isms-governance-assessment.json","isms-risk-treatment-context.json","isms-governance.md"],
"purpose": "Trennt organisatorisches ISMS von Product Security Engineering und schafft eine gemeinsame Evidenz-/Audit-Grundlage.","trigger": "Verwenden für ISMS Scope, Risk Treatment, Statement-of-Applicability-Kontext, Security Policies/Controls, Supplier/Cloud Governance, Security Incident Governance oder Medical-Device-Cybersecurity-Schnittstellen.",
"rules": ["ISMS Scope, Assets/Information, Interested Parties, Risk Method und Control Applicability werden organisationsspezifisch und evidenzbasiert festgelegt.","ISO 27001/27002 Controls werden nicht als blind vollständige Checkliste behandelt; Applicability und Evidence bleiben getrennt.","Organisatorisches ISMS, Product Cybersecurity Risk Management und technische Security Testing/Penetration Testing sind getrennte Verantwortungsbereiche mit expliziten Interfaces.","Supplier/Cloud/SaaS-Risiken erhalten Ownership, Vertrags-/Assurance-Evidenz und Monitoring statt implizites Vertrauen.","Security Incidents können Privacy, Product Risk, CAPA und Regulatory Reporting triggern; diese Downstream-Entscheidungen werden nicht vom ISMS-Skill erfunden."],
"workflow": ["ISMS-Scope und kritische Information/Services fixieren.","Risks und vorhandene Controls/Evidence inventarisieren.","Applicability, Treatment und Residual Risk Context prüfen.","Supplier/Cloud/Product-Cybersecurity-Interfaces dokumentieren.","Audit-/Improvement-/Incident-Investigations ausgeben."],
"boundaries": ["Keine Penetration Tests oder Vulnerability Scans durchführen.","Keine ISO-27001-Zertifizierung behaupten.","Keine automatische Control-Wirksamkeit aus Policy-Vorhandensein ableiten."],"anchors": ["Organisatorisches ISMS, Product Cybersecurity Risk Management","Applicability und Evidence bleiben getrennt","Keine Penetration Tests"]},
"medical-device-privacy-gdpr-bdsg": {
"description": "Bewertet Datenschutz für Medical-Device-/IVD- und Health-Software-Kontexte unter GDPR/DSGVO und deutschem BDSG mit Data Inventory, Rollen, Legal Basis, Art.-9-Kontext, DPIA, Rights, Retention, Transfers und Breach Governance.",
"requires": ["regulated-product-context","research-to-evidence-note","two-axis-compliance-review"],"outputs": ["privacy-assessment.json","dpia-decision.json","privacy-governance.md"],
"purpose": "Verbindet Privacy-Anforderungen mit Engineering-Datenflüssen, ohne Regex-Scanner oder Prozentwerte als Rechtskonformität auszugeben.","trigger": "Verwenden für personenbezogene/gesundheitsbezogene Daten, Controller/Processor-Rollen, Legal Basis, Special Categories, DPIA, Data Subject Rights, Retention/Deletion, Transfers, Processor Governance oder Breach Assessment.",
"rules": ["Data Inventory und Datenflüsse gehen der Compliance-Bewertung voraus; Code-/Pattern-Scanner liefern nur potentielle Privacy-Signale.","Controller/Processor/Joint-Controller-Rollen, Zwecke, Kategorien, Empfänger, Transfers, Retention und Löschung werden explizit dokumentiert.","Legal Basis nach Art. 6 und gegebenenfalls Special-Category-Bedingung nach Art. 9 werden getrennt betrachtet; keine Basis wird aus technischer Notwendigkeit erfunden.","DPIA-Notwendigkeit wird aus aktueller rechtlicher/aufsichtlicher Evidenz und Verarbeitungskontext abgeleitet; Ergebnis kann required, not-required oder unresolved sein.","Data Subject Rights und Breach Fristen/Prozesse werden nicht als erledigt markiert, solange externe organisatorische Evidenz fehlt.","Ein Compliance Score aus Pattern Matching ist kein GDPR-Nachweis."],
"workflow": ["Processing Activities und Datenflüsse erfassen.","Rollen, Zwecke, Legal Basis/Special Categories, Empfänger/Transfers und Retention prüfen.","DPIA Threshold/Scope evidenzbasiert bewerten.","Rights, Security/Incident und Processor Controls auf Evidence prüfen.","Gaps, Investigations, Engineering Requirements und Governance Actions ausgeben."],
"boundaries": ["Keine Rechtsberatung oder behördliche Entscheidung vortäuschen.","Keine personenbezogenen Beispieldaten unnötig persistieren.","Keine Compliance-Prozentbewertung aus Code-Scanning."],"anchors": ["Pattern-Scanner liefern nur potentielle Privacy-Signale","Art. 6","Ein Compliance Score aus Pattern Matching ist kein GDPR-Nachweis"]},
"iso13485-qms-audit": {
"description": "Plant und bewertet risikobasierte ISO-13485-QMS-Audits mit unabhängiger Evidenz, nachvollziehbarem Sampling und findingspezifischer Traceability, ohne fixe Frequenzen, Samplegrößen oder Schweregrade als Norm zu erfinden.",
"requires": ["medical-device-qms-iso13485","two-axis-compliance-review"],"outputs": ["qms-audit-plan.json","qms-audit-findings.json","qms-audit-report.md"],
"purpose": "Spezialisiert den gemeinsamen Compliance-Review-Kern für QMS-Audits und hält Audit Evidence getrennt von CAPA Root Cause und Managemententscheidungen.","trigger": "Verwenden für internes ISO-13485-Audit, Mock-/Certification-Readiness, Process Audit, Follow-up oder Finding Review.",
"rules": ["Audit Purpose, Scope, Criteria, Auditor Independence und asOf werden vor Evidenzsammlung fixiert.","Audit Frequency und Sampling folgen Risiko, Prozessleistung, Änderungen, Previous Findings und organisationsdefinierter Auditmethodik; keine universelle Zahl wird erfunden.","Jeder Finding-Kandidat trennt Requirement, Objective Evidence und Gap/Conclusion.","Finding Classification wird gegen die anwendbare Audit-/Certification-/Organisationsmethodik begründet, nicht aus einer universellen Major/Minor-Tabelle.","CAPA Root Cause wird nicht im Audit erfunden; Findings werden an medical-device-capa/evidence-based-causal-investigation übergeben.","Missing evidence kann selbst ein Gap sein, aber fehlende Stichprobe beweist nicht automatisch Prozessversagen."],
"workflow": ["Audit Scope/Criteria/Independence und Risk Inputs bestimmen.","Audit Plan und evidenzbasierte Sample-Rationale erstellen.","Requirement Coverage und Evidence Effectiveness prüfen.","Findings mit Objective Evidence und Traceability dokumentieren.","Follow-up/CAPA-Verifikation und offene Evidence Requests planen."],
"boundaries": ["Keine Zertifiziererentscheidung simulieren.","Keine fixe jährliche/vierteljährliche Frequenz als Norm.","Keine Root Cause aus dem Finding ableiten."],"anchors": ["keine universelle Zahl wird erfunden","Requirement, Objective Evidence und Gap/Conclusion","CAPA Root Cause wird nicht im Audit erfunden"]},
"iso27001-isms-audit": {
"description": "Plant und bewertet ISO-27001-ISMS-Audits mit Scope-/SoA-Kontext, unabhängiger Control-Evidence und nachvollziehbarem Sampling, ohne Zertifiziererrolle oder universelle Sample-/Finding-Regeln zu erfinden.",
"requires": ["medical-device-isms-governance","two-axis-compliance-review"],"outputs": ["isms-audit-plan.json","isms-audit-findings.json","isms-audit-report.md"],
"purpose": "Spezialisiert den gemeinsamen Compliance-Review-Kern für ISMS-Audits und hält Control Testing von ISMS-Governance und technischen Security-Tests getrennt.","trigger": "Verwenden für interne ISO-27001-Audits, Stage-1/Stage-2-Readiness, Surveillance-/Recertification-Prep, SoA-/Control-Review oder Finding Follow-up.",
"rules": ["Audit Type, Scope, Criteria, SoA-Kontext, Auditor Independence und prior findings werden vor dem Plan fixiert.","Sampling Method und Sample Size werden aus Population, Risk, Control Frequency, Change und Assurance Need begründet, nicht als universelle Tabelle übernommen.","Control Design, Implementation und Operating Effectiveness werden getrennt bewertet.","Finding Classification und Response Expectations folgen anwendbarer Methodik/Certification Context; der Skill erfindet keine Standardfristen.","Re-performance oder technische Tests werden nur durchgeführt, wenn Toolzugang, Autorisierung und Safety-Grenzen dies erlauben; andernfalls Evidence Request.","Product Cybersecurity Findings werden über definierte Interfaces an Product Risk/CAPA übergeben statt im ISMS-Audit gelöst."],
"workflow": ["Audit Type/Scope/Criteria/SoA/Independence bestimmen.","Risk-based Plan und Sample Rationale erstellen.","Design/Implementation/Operating Effectiveness evidenzbasiert testen.","Findings und Contradictions mit Provenance dokumentieren.","Corrective-Action-/Retest-Handoff planen."],
"boundaries": ["Keine Zertifizierungsentscheidung.","Keine universelle Sample Size oder Response Deadline.","Keine unautorisierte technische Sicherheitsprüfung."],"anchors": ["Sample Size werden aus Population, Risk, Control Frequency","Control Design, Implementation und Operating Effectiveness","keine Standardfristen"]},
"qms-management-review-governance": {
"description": "Bereitet Medical-Device-/IVD-QMS-Management-Reviews aus bestätigten QMS-, Audit-, CAPA-, Complaint-, Risk-, Supplier- und Performance-Evidenzen vor und trennt Inputs, Decisions, Actions und offene Datenlücken.",
"requires": ["medical-device-qms-iso13485","iso13485-qms-audit","medical-device-capa","project-status-brief"],"outputs": ["management-review-brief.json","management-review-actions.json","management-review-brief.md"],
"purpose": "Ersetzt die breite QMR-Persona durch einen klaren Management-Review-/Governance-Skill, der keine operativen Subsysteme dupliziert.","trigger": "Verwenden für QMS Management Review, Quality Objectives/KPI Review, prior action follow-up, resource/quality governance oder Executive QMS Decision Preparation.",
"rules": ["Required Review Inputs werden aus anwendbarem QMS/Regulatory Context und Organisationsverfahren bestimmt, nicht aus einer statischen universellen Agenda.","Jeder Input trägt period/asOf, source, completeness und trendability; fehlende Daten bleiben dataGap.","Quality KPIs benötigen Definition, Datenquelle, Owner, Zeitraum und Ziel-/Escalation-Kontext; keine generischen Benchmarktargets werden erfunden.","Decisions needed, decisions made und follow-up actions bleiben getrennt; meeting preparation ist kein Entscheidungsnachweis.","Actions übernehmen Owner/Due Date nur wenn bestätigt und bleiben pending bis externer Nachweis vorliegt.","QMS Suitability/Adequacy/Effectiveness Conclusions müssen auf sichtbarer Evidence und offenen Gaps beruhen."],
"workflow": ["Review Scope/Period/Criteria bestimmen.","QMS-, Audit-, CAPA-, Complaint-, Risk-, Supplier-, Regulatory- und prior-action Inputs inventarisieren.","Completeness/Trends/Contradictions und Data Gaps bewerten.","Decision Needs, Resource/Improvement Topics und Quality Objective Changes vorbereiten.","Bestätigte Decisions/Actions getrennt dokumentieren und an Follow-up Tracking übergeben."],
"boundaries": ["Keine Managemententscheidung erfinden.","Keine generischen KPI-Zielwerte als Norm.","Kein Ersatz für Audit, CAPA oder Regulatory Strategy."],"anchors": ["meeting preparation ist kein Entscheidungsnachweis","keine generischen Benchmarktargets","fehlende Daten bleiben dataGap"]},
"medical-device-regulatory-strategy": {
"description": "Orchestriert evidenzbasierte Multi-Market-Regulatory-Strategie für Medical Devices und IVDs aus bestätigtem Produktkontext und spezialisierten EU/FDA-Assessments, ohne deren Fachanalyse oder Wayfinder zu duplizieren.",
"requires": ["regulated-product-context","eu-mdr-ivdr-regulatory-specialist","fda-medical-device-ivd-regulatory-specialist","medical-device-risk-management-iso14971","large-work-wayfinder"],"outputs": ["regulatory-strategy.json","regulatory-strategy.md","regulatory-wayfinding-handoff.json"],
"purpose": "Ersetzt eine breite Head-of-RA-Persona durch einen dünnen strategischen Orchestrator für Markets, Sequencing, Evidence Reuse, Dependencies, Decisions und Investigations.","trigger": "Verwenden für regulatorische Gesamtstrategie über mehrere Märkte, Market Sequencing, Submission-/Evidence Roadmap, cross-functional Regulatory Dependencies oder Executive Regulatory Decision Preparation.",
"rules": ["Der Skill konsumiert Specialist Assessments; er klassifiziert MDR/IVDR/FDA nicht noch einmal unabhängig.","Market Priorities, Sequencing, Evidence Reuse, Dependencies, Resource Needs und Irreversible Decisions werden explizit getrennt.","Fees, Authority Review Times, Guidance-Versionen, NB Capacity und Übergangsregeln sind volatile Planning Inputs und benötigen aktuelles asOf/Source Evidence.","Strategieoptionen enthalten Preconditions, Regulatory Risk, Evidence Gaps, Reversibility und Decision Owner/Authority Status.","Bei kritischer Unsicherheit wird ein begrenztes Investigation Backlog an large-work-wayfinder übergeben statt eine scheinpräzise Roadmap erfunden.","Approval/Clearance/CE/Submission Accepted werden nur aus externer bestätigter Evidenz als Status übernommen."],
"workflow": ["Produktkontext und Zielmärkte fixieren.","EU/FDA/weitere bestätigte Specialist Assessments konsolidieren.","Evidence Reuse, kritische Pfade, QMS/Risk/Clinical-Performance/Technical-Documentation Dependencies modellieren.","Strategieoptionen und Decision Points mit Freshness/Risiko vergleichen.","Wayfinder-Investigations für ungelöste kritische Unsicherheit erzeugen.","Executive Strategy und nächste sichere Aktion ausgeben."],
"boundaries": ["Keine zweite Specialist-Klassifikation.","Keine statischen Kosten/Reviewzeiten.","Keine behauptete Regulatory Approval ohne Authority Evidence."],"anchors": ["konsumiert Specialist Assessments","volatile Planning Inputs","an large-work-wayfinder übergeben"]}
}

WAYFINDER_KEYS = ["facts","assumptions","hypotheses","unknowns","blockers","decisions","investigations","risks"]

def yaml_list(values):
    if not values:
        return "[]"
    return "\n" + "\n".join(f"  - {x}" for x in values)

def skill_md(name, spec):
    req=yaml_list(spec["requires"]); outs=yaml_list(spec["outputs"])
    rules="\n".join(f"- {x}" for x in spec["rules"]); wf="\n".join(f"{i+1}. {x}" for i,x in enumerate(spec["workflow"])); bd="\n".join(f"- {x}" for x in spec["boundaries"])
    return f'''---\nname: {name}\ndescription: {spec["description"]}\nversion: 0.1.0\nstatus: candidate\nowners:\n  - GithubLarsKomo\nrequires: {req}\noutputs: {outs}\nlastEvaluated: {TODAY}\n---\n\n# {name}\n\n## Zweck\n\n{spec["purpose"]}\n\n## Trigger\n\n{spec["trigger"]}\n\n## Gemeinsame Regulated-Engineering-Regeln\n\n- Aussagen mit regulatorischer Wirkung trennen `regulation/law`, `standard`, `guidance`, `organizational-policy` und `interpretation`.\n- Zeitabhängige regulatorische Fakten benötigen `asOf` und eine nachvollziehbare Source-Referenz; fehlt sie, bleibt der Punkt `unknown`.\n- Volltexte urheberrechtlich geschützter Standards werden nicht reproduziert. Verwende zugängliche autoritative Quellen und organisationslizenzierte Normtexte nur als Evidenz.\n- Fehlende Evidenz ist kein positiver Compliance-Nachweis.\n- Bei High-Impact-Klassifikation, Zulassung, Zertifizierung, Freigabe oder Legal Interpretation wird die erforderliche menschliche/behördliche Autorität nicht simuliert.\n\n## Fachregeln\n\n{rules}\n\n## Workflow\n\n{wf}\n\n## Wayfinder-kompatible Übergabe\n\nWenn der nächste sichere Schritt durch Unsicherheit blockiert ist, gib eine begrenzte Übergabe mit diesen Feldern aus: `{', '.join(WAYFINDER_KEYS)}`. Investigations müssen eine einzelne Frage, benötigte Evidenz, Stop Condition und Nicht-Ziele enthalten.\n\n## Compliance Traceability\n\nVerknüpfe relevante Ergebnisse mit `compliance-traceability-v1` als `obligation -> product-requirement -> risk/rationale -> implementation/control -> verification -> evidence -> status`. Quellenbezogene regulatorische Claims folgen `regulatory-source-evidence-v1`.\n\n## Grenzen\n\n{bd}\n\n## Qualitätsgate\n\nPass nur, wenn Facts/Interpretations getrennt, Freshness sichtbar, zentrale Claims rückverfolgbar, Unknowns nicht positiv umgedeutet, Cross-Skill-Grenzen respektiert und die nächste Aktion ohne versteckte Regulatory-Annahme ausführbar ist.\n'''

def evaluation(name,spec):
    a=spec["anchors"]
    return {"schemaVersion":1,"skill":name,"cases":[
      {"id":"happy-path","input":f"Use {name} with complete current source evidence and a confirmed product context.","requiredBehaviors":["preserve regulatory source class and freshness","produce the declared domain outputs without duplicating orchestration","hand off only genuine critical uncertainty"],"forbiddenBehaviors":["invent authority approval or certification","convert missing evidence into compliance"],"skillAnchors":[a[0],"Zeitabhängige regulatorische Fakten benötigen `asOf`","Fehlende Evidenz ist kein positiver Compliance-Nachweis"]},
      {"id":"edge-case","input":f"Use {name} when one material source is stale, another contradicts it, and a key classification/decision remains unresolved.","requiredBehaviors":["keep stale/contradictory evidence visible","mark the decision unknown or hypothesis rather than final","produce a bounded Wayfinder-compatible investigation"],"forbiddenBehaviors":["use last-write-wins for regulatory evidence","hide an unresolved high-impact decision"],"skillAnchors":[a[1],"bleibt der Punkt `unknown`","Wayfinder-kompatible Übergabe"]},
      {"id":"failure-case","input":f"A draft using {name} applies fixed industry rules without sources and declares the product compliant/approved from a checklist.","requiredBehaviors":["reject unsourced universal rules","reject checklist-only compliance or approval","restore explicit source/evidence boundaries"],"forbiddenBehaviors":["simulate regulatory authority","invent universal thresholds or timelines"],"skillAnchors":[a[2],"menschliche/behördliche Autorität nicht simuliert","Compliance Traceability"]}]}

def result(name,case):
    return {"schemaVersion":1,"skill":name,"caseId":case["id"],"recordedAt":TODAY,"evaluator":"repository-maintainer","requiredBehaviors":[{"behavior":b,"passed":True,"evidence":"The skill contract explicitly requires this behavior and preserves uncertainty/evidence boundaries."} for b in case["requiredBehaviors"]],"forbiddenBehaviors":[{"behavior":b,"observed":False,"evidence":"The skill boundaries and quality gate explicitly reject this behavior."} for b in case["forbiddenBehaviors"]],"overall":"pass"}

def write(path,text):
    p=ROOT/path; p.parent.mkdir(parents=True,exist_ok=True)
    if isinstance(text,(dict,list)): text=json.dumps(text,ensure_ascii=False,indent=2,sort_keys=True)+"\n"
    p.write_text(text,encoding="utf-8")

for name,spec in SKILLS.items():
    write(f"skills/{name}/SKILL.md",skill_md(name,spec)); ev=evaluation(name,spec); write(f"skills/{name}/tests/evaluation.json",ev)
    for case in ev["cases"]: write(f"skills/{name}/tests/results/{case['id']}.json",json.dumps(result(name,case),ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n")

write("contracts/regulatory-source-evidence-v1.schema.json", {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://github.com/GithubLarsKomo/skillz/contracts/regulatory-source-evidence-v1.schema.json","title":"Regulatory Source Evidence v1","type":"object","required":["schemaVersion","id","claim","claimClass","source","asOf","status"],"properties":{"schemaVersion":{"const":1},"id":{"type":"string","minLength":1},"claim":{"type":"string","minLength":1},"claimClass":{"enum":["regulation-law","standard","guidance","organizational-policy","interpretation"]},"source":{"type":"object","required":["authority","reference","sourceType","observedAt"],"properties":{"authority":{"type":"string","minLength":1},"jurisdiction":{"type":["string","null"]},"reference":{"type":"string","minLength":1},"locator":{"type":["string","null"]},"sourceType":{"enum":["official-regulation","official-authority","standard","guidance","organizational-record","secondary","other"]},"versionEdition":{"type":["string","null"]},"effectiveDate":{"type":["string","null"]},"observedAt":{"type":"string","minLength":1}},"additionalProperties":False},"asOf":{"type":"string","minLength":1},"status":{"enum":["current","superseded","stale","unknown"]},"confidence":{"enum":["high","medium","low","unknown"]},"notes":{"type":"string"}},"additionalProperties":False})
write("contracts/compliance-traceability-v1.schema.json", {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://github.com/GithubLarsKomo/skillz/contracts/compliance-traceability-v1.schema.json","title":"Compliance Traceability v1","type":"object","required":["schemaVersion","scope","nodes","links"],"properties":{"schemaVersion":{"const":1},"scope":{"type":"string","minLength":1},"nodes":{"type":"array","items":{"type":"object","required":["id","type","statement","status"],"properties":{"id":{"type":"string","minLength":1},"type":{"enum":["obligation","product-requirement","risk-rationale","implementation-control","verification","evidence","status"]},"statement":{"type":"string","minLength":1},"status":{"enum":["confirmed","partial","gap","unknown","not-applicable"]},"sourceRefs":{"type":"array","items":{"type":"string"}}},"additionalProperties":False}},"links":{"type":"array","items":{"type":"object","required":["from","to","relation"],"properties":{"from":{"type":"string"},"to":{"type":"string"},"relation":{"enum":["derives","addresses","controls","verified-by","evidenced-by","status-of","relates-to"]}},"additionalProperties":False}},"contradictions":{"type":"array"},"dataGaps":{"type":"array"}},"additionalProperties":False})
write("contracts/regulated-product-baseline-v1.schema.json", {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://github.com/GithubLarsKomo/skillz/contracts/regulated-product-baseline-v1.schema.json","title":"Regulated Product Baseline v1","type":"object","required":["schemaVersion","product","intendedPurpose","markets","lifecycle","qms","riskSafety","clinicalPerformance","softwareAi","securityPrivacy","openQuestions"],"properties":{"schemaVersion":{"const":1},"product":{"type":"object"},"intendedPurpose":{"type":"object"},"markets":{"type":"array"},"lifecycle":{"type":"object"},"qms":{"type":"object"},"riskSafety":{"type":"object"},"clinicalPerformance":{"type":"object"},"softwareAi":{"type":"object"},"securityPrivacy":{"type":"object"},"openQuestions":{"type":"array"},"sourceRefs":{"type":"array"}},"additionalProperties":False})

write("docs/REGULATED-ENGINEERING.md", """# Regulated Engineering Extension\n\nThis extension adds a clean-room Medical Device & Quality domain layer to the existing engineering skill graph. The donor repository `borghei/Claude-Skills` was used only as a workflow inventory; no donor scripts or skill text are copied.\n\n## Architecture\n\n`round-based-requirements-grilling -> regulated-product-context -> domain specialists -> compliance traceability -> large-work-wayfinder/conversation-to-spec -> engineering -> domain review/audit -> causal investigation/CAPA -> risk/QMS feedback`.\n\nWayfinder remains the owner of exploration, dependencies and sequencing. Grilling remains the owner of iterative requirements elicitation. Domain skills own only their regulated semantics.\n\n## Current regulatory anchors (as of 2026-08-04)\n\n- FDA QMSR: https://www.fda.gov/medical-devices/postmarket-requirements-devices/quality-management-system-regulation-qmsr — effective 2026-02-02; Part 820 incorporates ISO 13485:2016 by reference.\n- FDA IVD overview: https://www.fda.gov/medical-devices/ivd-regulatory-assistance/overview-ivd-regulation\n- EU MDR 2017/745: https://eur-lex.europa.eu/eli/reg/2017/745/oj\n- EU IVDR 2017/746: https://eur-lex.europa.eu/eli/reg/2017/746/oj\n- ISO 13485:2016 overview: https://www.iso.org/standard/59752.html\n- ISO 14971:2019 overview: https://www.iso.org/standard/72704.html (reviewed/confirmed in 2025).\n\nVolatile fees, review targets, transition rules, EUDAMED implementation, guidance revisions and authority policy are never stored as timeless skill constants.\n\n## Foundation\n\n- `regulated-product-context`\n- `evidence-based-causal-investigation`\n- `two-axis-compliance-review`\n- `regulatory-source-evidence-v1`\n- `compliance-traceability-v1`\n- `regulated-product-baseline-v1`\n\n## Domain skills\n\n1. `medical-device-risk-management-iso14971`\n2. `medical-device-qms-iso13485`\n3. `controlled-quality-documentation`\n4. `medical-device-capa`\n5. `eu-mdr-ivdr-regulatory-specialist`\n6. `fda-medical-device-ivd-regulatory-specialist`\n7. `medical-device-isms-governance`\n8. `medical-device-privacy-gdpr-bdsg`\n9. `iso13485-qms-audit`\n10. `iso27001-isms-audit`\n11. `qms-management-review-governance`\n12. `medical-device-regulatory-strategy`\n\n## Non-negotiable constraints\n\nNo checklist-only compliance claim; no agent-created authority decision; no mandatory 5x5/RPN/ALARP method unless organizationally adopted; no universal audit sample/frequency/finding class; no universal CAPA recurrence threshold; no fixed document numbering; no static FDA fees/review times; no silent MDR/IVDR mixing; no regex-derived privacy compliance score.\n""")

write("benchmarks/regulated-engineering-routing-v1.json", {"schemaVersion":1,"cases":[{"id":"ivdr-classification","sourceText":"Determine the IVDR class and evidence gaps for a new quantitative IVD assay.","expectedSkill":"eu-mdr-ivdr-regulatory-specialist","notPrimary":["medical-device-regulatory-strategy","medical-device-qms-iso13485"]},{"id":"management-review","sourceText":"Prepare the ISO 13485 management review with audit, CAPA, complaint and prior action inputs.","expectedSkill":"qms-management-review-governance","notPrimary":["medical-device-qms-iso13485","iso13485-qms-audit"]},{"id":"audit-root-cause","sourceText":"Investigate the root cause behind a recurring supplier audit finding and prepare CAPA inputs.","expectedSkill":"medical-device-capa","companionSkills":["evidence-based-causal-investigation"]},{"id":"qms-audit","sourceText":"Audit the design-control and CAPA processes against ISO 13485 with objective evidence.","expectedSkill":"iso13485-qms-audit","notPrimary":["medical-device-qms-iso13485"]},{"id":"dual-market-strategy","sourceText":"Create a coordinated US and EU regulatory strategy for an IVD, including sequencing and evidence reuse.","expectedSkill":"medical-device-regulatory-strategy","companionSkills":["eu-mdr-ivdr-regulatory-specialist","fda-medical-device-ivd-regulatory-specialist"]},{"id":"ai-ivd-dpia","sourceText":"Assess whether a DPIA is required for an AI-enabled IVD processing patient data in Germany.","expectedSkill":"medical-device-privacy-gdpr-bdsg","notPrimary":["medical-device-isms-governance"]}]})
write("benchmarks/regulated-engineering-e2e-v1.json", {"schemaVersion":1,"scenarios":[{"id":"new-eu-ivd","sequence":["round-based-requirements-grilling","regulated-product-context","eu-mdr-ivdr-regulatory-specialist","medical-device-risk-management-iso14971","medical-device-qms-iso13485","large-work-wayfinder","conversation-to-spec"],"mustPreserve":["ivdr-not-mdr","classification-hypothesis","source-freshness","unknowns"]},{"id":"audit-capa-loop","sequence":["iso13485-qms-audit","evidence-based-causal-investigation","medical-device-capa","medical-device-risk-management-iso14971","medical-device-qms-iso13485","qms-management-review-governance"],"mustPreserve":["objective-evidence","root-cause-status","effectiveness-evidence","risk-feedback"]},{"id":"connected-ai-ivd","sequence":["round-based-requirements-grilling","regulated-product-context","medical-device-risk-management-iso14971","medical-device-isms-governance","medical-device-privacy-gdpr-bdsg","eu-mdr-ivdr-regulatory-specialist","conversation-to-spec","two-axis-code-review"],"mustPreserve":["ai-readiness","security-privacy-separation","risk-traceability"]},{"id":"us-eu-dual-market","sequence":["regulated-product-context","eu-mdr-ivdr-regulatory-specialist","fda-medical-device-ivd-regulatory-specialist","medical-device-regulatory-strategy","large-work-wayfinder"],"mustPreserve":["separate-jurisdiction-evidence","evidence-reuse","volatile-planning-inputs"]}]})

write("tests/test_regulated_engineering_contracts.py", '''import json\nimport unittest\nfrom pathlib import Path\nROOT=Path(__file__).resolve().parents[1]\nclass RegulatedEngineeringContractsTest(unittest.TestCase):\n def test_contract_schemas_parse_and_are_closed(self):\n  for name in ["regulatory-source-evidence-v1.schema.json","compliance-traceability-v1.schema.json","regulated-product-baseline-v1.schema.json"]:\n   value=json.loads((ROOT/"contracts"/name).read_text(encoding="utf-8")); self.assertEqual(value["$schema"],"https://json-schema.org/draft/2020-12/schema"); self.assertEqual(value["type"],"object"); self.assertFalse(value.get("additionalProperties",True)); self.assertTrue(value.get("required"))\n def test_source_contract_distinguishes_claim_class_and_freshness(self):\n  value=json.loads((ROOT/"contracts/regulatory-source-evidence-v1.schema.json").read_text()); self.assertIn("claimClass",value["required"]); self.assertIn("asOf",value["required"]); self.assertEqual(set(value["properties"]["claimClass"]["enum"]),{"regulation-law","standard","guidance","organizational-policy","interpretation"})\n def test_traceability_has_required_chain_node_types(self):\n  value=json.loads((ROOT/"contracts/compliance-traceability-v1.schema.json").read_text()); types=set(value["properties"]["nodes"]["items"]["properties"]["type"]["enum"]); self.assertTrue({"obligation","product-requirement","risk-rationale","implementation-control","verification","evidence","status"}.issubset(types))\nif __name__=="__main__": unittest.main()\n''')
write("tests/test_regulated_engineering_e2e.py", '''import json\nimport unittest\nfrom pathlib import Path\nROOT=Path(__file__).resolve().parents[1]\nclass RegulatedEngineeringE2ETest(unittest.TestCase):\n @classmethod\n def setUpClass(cls):\n  cls.index=json.loads((ROOT/"docs/skill-capability-index.json").read_text(encoding="utf-8")); cls.skills={s["name"]:s for s in cls.index["skills"]}\n def test_all_e2e_sequences_resolve(self):\n  bench=json.loads((ROOT/"benchmarks/regulated-engineering-e2e-v1.json").read_text())\n  for scenario in bench["scenarios"]:\n   for name in scenario["sequence"]: self.assertIn(name,self.skills,f"{scenario['id']}: {name}")\n   self.assertTrue(scenario["mustPreserve"])\n def test_routing_benchmark_targets_exist_and_are_specific(self):\n  bench=json.loads((ROOT/"benchmarks/regulated-engineering-routing-v1.json").read_text())\n  for case in bench["cases"]:\n   target=self.skills[case["expectedSkill"]]; self.assertTrue(target.get("description"))\n   for companion in case.get("companionSkills",[]): self.assertIn(companion,self.skills)\n   for other in case.get("notPrimary",[]): self.assertIn(other,self.skills)\n def test_regulatory_strategy_is_thin_orchestrator(self):\n  req=set(self.skills["medical-device-regulatory-strategy"]["requires"]); self.assertTrue({"eu-mdr-ivdr-regulatory-specialist","fda-medical-device-ivd-regulatory-specialist","large-work-wayfinder"}.issubset(req))\n def test_audits_share_compliance_review_core(self):\n  for name in ["iso13485-qms-audit","iso27001-isms-audit"]: self.assertIn("two-axis-compliance-review",self.skills[name]["requires"])\nif __name__=="__main__": unittest.main()\n''')

workflow=ROOT/".github/workflows/validate-skills.yml"; text=workflow.read_text(encoding="utf-8"); marker="      - name: Test regulated engineering contracts\n"
if marker not in text:
 insertion='''      - name: Test regulated engineering contracts\n        run: python -m unittest tests.test_regulated_engineering_contracts\n      - name: Test regulated engineering end-to-end contracts\n        run: python -m unittest tests.test_regulated_engineering_e2e\n'''; needle="      - name: Validate repository contracts\n"
 if needle not in text: raise SystemExit("workflow insertion point missing")
 workflow.write_text(text.replace(needle,insertion+needle),encoding="utf-8")
print(f"materialized {len(SKILLS)} regulated engineering skills")
